#!/bin/zsh
cd server

JAVA=/Users/paulinobruno/.sdkman/candidates/java/8.0.222-zulu/bin/java 

docker-compose up & sleep 5
$JAVA -jar cdcreact-1.0.0-SNAPSHOT.jar & sleep 10

echo "(Press Enter to interrupt...)"
read

PID=`ps | grep java | grep cdcreact-1.0.0-SNAPSHOT.jar | cut -c 1-5`
echo "Matando processo $PID"
kill -9 $PID

docker-compose down

