version: '2.1'

services:
  db:
    image: mariadb:10.2
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ss -l -p -n | grep 3306 || exit 1
      interval: 1s
      timeout: 30s
      retries: 30
    volumes:
      - store:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  m2repo:
    external: true
  ivy2:
    external: true
  store:
